---
router_id: 10.255.0.1
local_as: 65501
bgp_neighbors:
  - neighbor_ip: 10.255.0.50
    remote_as: 65503
  - neighbor_ip: 10.255.0.46
    remote_as: 65502
ospf_interfaces:
  - interface_name: GigabitEthernet0/0/0.455
  - interface_name: GigabitEthernet0/0/1.355
interfaces:
  - interface_name: GigabitEthernet0/0/0.455
    ip_address: 10.255.0.49
    subnet_mask: 255.255.255.252
  - interface_name: GigabitEthernet0/0/1.355
    ip_address: 10.255.0.45
    subnet_mask: 255.255.255.252
