---
ansible_host: 10.99.2.51
bgp_config:
  as_number: "65501"
  bgp:
    router_id:
      address: "10.0.0.1"
  neighbors:
    - neighbor_address: "10.255.0.50"
      remote_as: "65503"
    - neighbor_address: "10.255.0.46"
      remote_as: "65502"

interfaces:
  - name: GigabitEthernet0/0/0.455
    description: "p2p to aggregate-noord"
    ip: 10.255.0.49
    mask: 255.255.255.252
    encapsulation: 455
  - name: Tunnel1
    description: "p2p to aggregate-zuid"
    ip: 10.255.0.45
    mask: 255.255.255.252
    encapsulation: 355

server_routers:
  - { name: "Limburg", vlan: 400, p2p_subnet: "172.24.255.252" }
  - { name: "N Brabant", vlan: 405, p2p_subnet: "172.25.255.252" }
  - { name: "Gelderland", vlan: 410, p2p_subnet: "172.26.255.252" }
  - { name: "Zeeland", vlan: 415, p2p_subnet: "172.27.255.252" }
  - { name: "Z Holland", vlan: 460, p2p_subnet: "172.28.255.252" }
  - { name: "ABC", vlan: 465, p2p_subnet: "172.29.255.252" }
  - { name: "Groningen", vlan: 430, p2p_subnet: "172.19.255.252" }
  - { name: "Friesland", vlan: 435, p2p_subnet: "172.23.255.252" }
  - { name: "Drenthe", vlan: 440, p2p_subnet: "172.17.255.252" }
  - { name: "Overijssel", vlan: 445, p2p_subnet: "172.21.255.252" }
